import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:['400','500','600','700']
});

// const geistMono = Outfit({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
     
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
